# Generated by Django 5.2.7 on 2025-10-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_create_shippers_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the consignee', max_length=255)),
                ('address', models.TextField(help_text='Address of the consignee')),
                ('postal_code', models.CharField(help_text='Postal code of the consignee', max_length=25)),
                ('city', models.CharField(help_text='City of the consignee', max_length=100)),
                ('country', models.CharField(help_text='Country of the consignee', max_length=100)),
                ('phone', models.CharField(help_text='Phone number of the consignee', max_length=20)),
                ('email', models.EmailField(help_text='Email address of the consignee', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consignee',
                'verbose_name_plural': 'Consignees',
                'db_table': 'consignees',
                'ordering': ['name'],
            },
        ),
    ]
