# Generated by Django 5.2.7 on 2025-10-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_create_consignees_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_body', models.JSONField(help_text='JSON data of the shipment request')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the shipment request', max_length=20)),
                ('retries', models.PositiveIntegerField(default=0, help_text='Number of retry attempts made')),
                ('last_retried_at', models.DateTimeField(blank=True, help_text='Timestamp of the last retry attempt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipment Request',
                'verbose_name_plural': 'Shipment Requests',
                'db_table': 'shipment_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
