# Generated by Django 5.2.7 on 2025-10-18 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_create_courier_configs_table'),
        ('shipment', '0003_create_shipment_requests_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_external_id', models.CharField(help_text='External ID provided by the courier service', max_length=255, unique=True)),
                ('reference_number', models.CharField(help_text='Reference number for this shipment', max_length=255, unique=True)),
                ('height', models.PositiveIntegerField(help_text='Height of the shipment')),
                ('width', models.PositiveIntegerField(help_text='Width of the shipment')),
                ('length', models.PositiveIntegerField(help_text='Length of the shipment')),
                ('dimension_unit', models.CharField(help_text='Unit of measurement for dimensions (e.g., cm, in)', max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight of the shipment', max_digits=10)),
                ('weight_unit', models.CharField(help_text='Unit of measurement for weight (e.g., kg, lb)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consignee', models.ForeignKey(help_text='The consignee (receiver) of this shipment', on_delete=django.db.models.deletion.CASCADE, to='shipment.consignee')),
                ('courier', models.ForeignKey(help_text='The courier service handling this shipment', on_delete=django.db.models.deletion.CASCADE, to='core.courier')),
                ('shipment_type', models.ForeignKey(help_text='The type of shipment', on_delete=django.db.models.deletion.CASCADE, to='core.shipmenttype')),
                ('shipper', models.ForeignKey(help_text='The shipper (sender) of this shipment', on_delete=django.db.models.deletion.CASCADE, to='shipment.shipper')),
                ('route', models.ForeignKey(help_text='The route of this shipment', on_delete=django.db.models.deletion.CASCADE, to='core.route')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'db_table': 'shipments',
                'ordering': ['-created_at'],
            },
        ),
    ]
