# Generated by Django 5.2.7 on 2025-10-18 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_create_courier_configs_table'),
        ('shipment', '0003_create_shipment_requests_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_external_id', models.CharField(max_length=255, unique=True)),
                ('reference_number', models.CharField(max_length=255, unique=True)),
                ('height', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('length', models.PositiveIntegerField()),
                ('dimension_unit', models.CharField(max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_unit', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.consignee')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courier')),
                ('shipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shipmenttype')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.shipper')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'db_table': 'shipments',
                'ordering': ['-created_at'],
            },
        ),
    ]
