# Generated by Django 5.2.7 on 2025-10-20 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0005_alter_weight_field_to_decimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(help_text='Reference number for this label', max_length=255)),
                ('url', models.URLField(help_text='URL to download the label', max_length=500)),
                ('format', models.CharField(help_text='Format of the label (e.g., PDF, PNG, ZPL)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this label is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.ForeignKey(help_text='The shipment this label belongs to', on_delete=django.db.models.deletion.CASCADE, to='shipment.shipment')),
            ],
            options={
                'verbose_name': 'Shipment Label',
                'verbose_name_plural': 'Shipment Labels',
                'db_table': 'shipment_labels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shipmentlabel',
            index=models.Index(fields=['shipment_id'], name='shipment_la_shipmen_8f3ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentlabel',
            index=models.Index(fields=['reference_number'], name='shipment_la_referen_d80468_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentlabel',
            index=models.Index(fields=['is_active'], name='shipment_la_is_acti_4362da_idx'),
        ),
    ]
