# Generated by Django 5.2.7 on 2025-10-20 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0006_create_shipment_labels_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text='Current status of the shipment (e.g., in_transit, delivered, exception)', max_length=100)),
                ('address', models.CharField(blank=True, help_text='Address where the status update occurred', max_length=500, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code of the location', max_length=20, null=True)),
                ('country', models.CharField(blank=True, help_text='Country where the status update occurred', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.ForeignKey(help_text='The shipment this status update belongs to', on_delete=django.db.models.deletion.CASCADE, to='shipment.shipment')),
            ],
            options={
                'verbose_name': 'Shipment Status',
                'verbose_name_plural': 'Shipment Statuses',
                'db_table': 'shipment_statuses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shipment_id'], name='shipment_st_shipmen_9c894a_idx'), models.Index(fields=['status'], name='shipment_st_status_ebbd5f_idx'), models.Index(fields=['created_at'], name='shipment_st_created_f4d9c6_idx')],
            },
        ),
    ]
