# Generated by Django 5.2.7 on 2025-10-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_create_couriers_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the shipment type (e.g., normal, urgent)', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipment Type',
                'verbose_name_plural': 'Shipment Types',
                'db_table': 'shipment_types',
                'ordering': ['name'],
            },
        ),
    ]
