# Generated by Django 5.2.7 on 2025-10-18 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_shipment_types_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierShipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(help_text='The courier service', on_delete=django.db.models.deletion.CASCADE, to='core.courier')),
                ('shipment_type', models.ForeignKey(help_text='The shipment type supported by this courier', on_delete=django.db.models.deletion.CASCADE, to='core.shipmenttype')),
            ],
            options={
                'verbose_name': 'Courier Shipment Type',
                'verbose_name_plural': 'Courier Shipment Types',
                'db_table': 'courier_shipment_types',
                'ordering': ['courier__name', 'shipment_type__name'],
                'unique_together': {('courier', 'shipment_type')},
            },
        ),
    ]
