# Generated by Django 5.2.7 on 2025-10-18 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_create_routes_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this route is currently active for this courier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(help_text='The courier service', on_delete=django.db.models.deletion.CASCADE, to='core.courier')),
                ('route', models.ForeignKey(help_text='The route supported by this courier', on_delete=django.db.models.deletion.CASCADE, to='core.route')),
            ],
            options={
                'verbose_name': 'Courier Route',
                'verbose_name_plural': 'Courier Routes',
                'db_table': 'courier_routes',
                'ordering': ['courier__name', 'route__origin', 'route__destination'],
                'unique_together': {('courier', 'route')},
            },
        ),
    ]
