# Generated by Django 5.2.7 on 2025-10-18 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_create_courier_routes_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(help_text="Base URL for the courier's API")),
                ('_api_key', models.TextField(help_text='Encrypted API key for authentication')),
                ('_api_secret', models.TextField(blank=True, help_text='Encrypted API secret for authentication (optional)', null=True)),
                ('_username', models.TextField(blank=True, help_text='Encrypted username for authentication (optional)', null=True)),
                ('_password', models.TextField(blank=True, help_text='Encrypted password for authentication (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(help_text='The courier this configuration belongs to', on_delete=django.db.models.deletion.CASCADE, to='core.courier')),
            ],
            options={
                'verbose_name': 'Courier Configuration',
                'verbose_name_plural': 'Courier Configurations',
                'db_table': 'courier_configs',
                'ordering': ['courier__name'],
                'unique_together': {('courier',)},
            },
        ),
    ]
